sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: GkeHQf1ipgPkfS3GhhXP4wbadlozzHrHKGsKG8ceFXKjQ9iUXzkFy3qiH9qw6d4+qvcPkoemYWH5eLlZ3Wua1NLMUm2kbYQy3wJkKEnuhs1QAMcCeB9U4RkQU0d2n+WKMQBxgfvlxJINqwzhSDjKKrY8+c1kp4B2S2/fTPlqwQYqose5gFsJUrO2bubTQmk6/aIRzM8LpXzAjb/8gSJqJAP9t8kOc60MVucQT2pdyNBTk5qH5Y5pLNBjMDbdcpxULghVvBjyYyO3iOV1vrtzbyQfRLAXShXhDvgOlptHj6MMHaGAHMZxM0lfkuq9Bvj8SCsZmzIrS3SbWkFHivhj0ISD7L+Hx7hynrZnsrhz3EfGGTSHPzT4DuIq6yXGMM17MPEA4YbqJXXkoblWNJpuVmnqnEW0lDJ0uCauzEH98ddcoxwMFNga86NFW0ySRW6p9cbxHWwMW3U1hwWpFD1R+CqFUwOKeYNQDG+4of/NRHYZqdzJfZeAByVeiXcacPMxCtadivRocIwMbVjp9k7q+JgO4FCc4U17mDN1pPB+Du8UfLy6PFpm/lECFkmmDISGmvEFuZvBiw47iiVaPTTwWv2PpOEi3p5Ruv00robem/LcWdnW3Sb6N3RATwZgTpfC44t7VcEDknq/1xfn1r0ulOxMLx7SSEhGa4xzuPTRwSs=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: SqnKe5EM20QL9UT8qGfTGbFQK9waMK6FyzR2eWGpRw/v/r4I9ulJ3tRpUhv4VT2BjGb8ohoD8LeeWVrnva6cq3Qfu2FiSSj/MjQkpFNLDiOyjJbY5OB/nB2frGfOop2kbbFydLLxqV4BAaRHOQfDI3pUAXNPoYMP4/WryjAeKYvLdEM2zw0huyCooRKV0ChzkqBloGJnjfB67nCV6Z4dvc59QYIkhmWUm15wmNY02KqkcCuin6Jie5zzPspOMwkXQr2yD93kwMim0tdBt2Z6ODdfu/mVxj6ErC1Sf2rhq45MBXkWn43/ZldpYjWFRQNmc5wdVFDo8otdDlV0cpneraRGpPoAwtlKa0O7umPZas42CuqhG4VQ1VeApiLYfGNHDoy0JEZIaYHXFp7ATAbg1/tmmb48lUnG4Hn/wvcAgY6KaBESTKXU0Ise5HwAF97ZUlVBR7u2nbVBsWvYxdWu0Vy+3c90E2FAQBDjCv0mfnwCAAQ+7wM+Vhh/Ce+meSFY2/wQcuIO0xTZ8a3J2QLHenJBk2HqE198LwyXOrUDlubWy9cnOYxUjim4dL8tIoxgGimDy0Ts9ZfCtD/c6rguUzz6s2knXHCPj+suC5OMlxQbJoYWCseh8alUYmuarG4uKE8d1/QV1nG74d0xaJO8kriuXCxsiF1gqKUETjqk8X0=
